---
- hosts: all
  roles:

  # osx config
  - role: dock
    apps:
    - /Applications/Atom.app
    - /Applications/Google Chrome.app
    - /Applications/Spotify.app
    - /Applications/iTerm.app
    - /Applications/Dash.app
    - /Applications/Zotero.app
    - /Applications/Skim.app
    folders:
    - path: ~/
    - path: ~/Downloads
      sort: datemodified
  - role: dashboard
    disabled: YES

  # fonts
  - role: cask_package
    tap: caskroom/fonts
    package_name: font-source-code-pro
  - role: cask_package
    tap: caskroom/fonts
    package_name: font-sauce-code-powerline

  # cli
  # shell tooling
  - role: git
    git_user_name: Tahir Butt
    git_user_email: tahir.butt@gmail.com
  - role: legit
  - role: hub
  - role: brew_package
    package_name: vim
  ## languages
  - role: brew_package
    package_name: node
  - role: rbenv
  - role: npm_package
    package_name: grunt
  - role: npm_package
    package_name: bower
  - role: brew_package
    package_name: android-sdk
  # - role: brew_package
  #   package_name: ansible # Hey ! Already there !

  # gui
  ## tools
  - role: cask_package
    package_name: the-unarchiver
  - role: cask_package
    package_name: spectacle
  - role: cask_package
    package_name: handbrake
  ## sync
  - role: cask_package
    package_name: dropbox
  - role: cask_package
    package_name: google-drive
  ## work
  - role: cask_package
    package_name: adium
  - role: cask_package
    package_name: cord
  - role: cask_package
    package_name: spotify
  - role: cask_package
    package_name: google-hangouts
  ## text editors
  - role: cask_package
    package_name: atom
  - role: cask_package
    package_name: macvim
  # academic
  - role: cask_package
    package_name: zotero
  - role: cask_package
    package_name: bibdesk
  - role: cask_package
    package_name: libreoffice
