---
- hosts: all
  roles:

  # osx config
  - role: dock
    apps:
    - /Applications/Google Chrome.app
    folders:
    - path: ~/
    - path: ~/Downloads
    - path: ~/Dropbox
      sort: datemodified
  - role: dashboard
    disabled: YES

  # fonts
  - role: cask_package
    tap: caskroom/fonts
    package_name: font-source-code-pro
  - role: cask_package
    tap: caskroom/fonts
    package_name: font-sauce-code-powerline
  - role: cask_package
    tap: caskroom/fonts
    package_name: font-inconsolata
  - role: cask_package
    tap: caskroom/fonts
    package_name: font-ubuntu

  # cli
  # shell tooling
  - role: git_config
    git_user_name: Tahir Butt
    git_user_email: tahir.butt@gmail.com
  - role: legit
  - role: hub
  - role: brew_package
    package_name: tmux
  - role: brew_package
    package_name: vim
  - role: maximum_awesome
  - role: oh_my_zsh
  ## languages
  - role: brew_package
    package_name: node
  - role: rbenv
  - role: npm_package
    package_name: grunt
  - role: npm_package
    package_name: bower
  ## tools
  - role: brew_package
    package_name: apg # password generator
  - role: brew_package
    package_name: djvu2pdf
  - role: brew_package
    package_name: docker
  - role: brew_package
    package_name: docker-machine
  - role: brew_package
    package_name: docker-compose
  - role: brew_package
    package_name: exiftool
  - role: brew_package
    package_name: youtube-dl
  - role: brew_package
    package_name: tree


  # - role: brew_package
  #   package_name: ansible # Hey ! Already there !

  # gui
  ## basics
  - role: cask_package
    package_name: dropbox
  - role: cask_package
    package_name: google-chrome
  - role: cask_package
    package_name: spotify
  - role: cask_package
    package_name: google-photos-backup
  - role: cask_package
    package_name: skype
  - role: cask_package
    package_name: slack
  - role: cask_package
    package_name: soulseek
  - role: cask_package
    package_name: vlc
  - role: cask_package
    package_name: iterm2
  ## tools
  - role: cask_package
    package_name: the-unarchiver
  - role: cask_package
    package_name: handbrake
  - role: cask_package
    package_name: transmission
  - role: cask_package
    package_name
  ## sync
  - role: cask_package
    package_name: dropbox
  - role: cask_package
    package_name: google-drive
  ## text editors
  - role: cask_package
    package_name: atom
  - role: cask_package
    package_name: macvim
  - role: cask_package
    package_name: scrivener
  # academic
  - role: cask_package
    package_name: zotero
  - role: cask_package
    package_name: firefox # TODO: install extensions for Zotero
  - role: cask_package
    package_name: pandoc
  - role: cask_package
    package_name: skim
  # dev
  - role: cask_package
    package_name: virtualbox
  - role: cask_package
    package_name: vagrant
  - role: cask_package
    package_name: basictex
